[package]
name = "activities"
version = "0.1.0"
edition = "2021"

[lib]
name="demo"
path = "src/demolib.rs"

[dependencies]
chrono = "0.4.34"
thiserror = "1.0"
crossbeam-channel = "0.5"
colored = "*"


